/*
 * user_interface.c
 *
 * Created: 12/18/2024 4:02:24 PM
 *  Author: tyler
 */ 

#include <avr/io.h>
#define F_CPU 4000000UL
#include <util/delay.h>
#include <stdio.h>
#include <avr/interrupt.h>
#include "main.h"


/* ISR to conduct loaded and unloaded tests and display results */
ISR(PORTC_PORT_vect){
		cli();
		VPORTC_INTFLAGS = 0x10; //clear interrupt flag
		conduct_test();
		sei(); //resume interrupts
}

//***************************************************************************
//
// Function Name : "display_battery_voltages_LOADED_and_UNLOADED;
// Target MCU : AVR128DB48
// DESCRIPTION
// Reads the battery cell voltages when unloaded and after benig 
// loaded with 500A and displays them on the LCD
//
// Inputs : NONE
//
// Outputs : NONE
//
//
//**************************************************************************
void conduct_test(void)
{
	/* Display a loading screen... */
	clear_lcd();
	sprintf(dsp_buff1, "Initiating Test.....");
	update_lcd();

	// read voltage of each cell and store in array when unloaded
	UNLOADED_battery_voltages[0] = batteryCell_read(0);   
	UNLOADED_battery_voltages[1] = batteryCell_read(5);	// change from PD1 to PD5 because OPAMP uses PD1 and PD4
	UNLOADED_battery_voltages[2] = batteryCell_read(2);
	UNLOADED_battery_voltages[3] = batteryCell_read(3);	
	
	// Delay for 3 seconds
	_delay_ms(1000);
	_delay_ms(1000); 
	_delay_ms(1000); 
	
	/* Tell user to rotate knob of carbon pile... */
	clear_lcd();
	sprintf(dsp_buff1, "Rotate Knob until"); 
	sprintf(dsp_buff2, "beeping sound is"); 
	sprintf(dsp_buff3, "heard");
	update_lcd();
	
	set_Fan_PWM(75);
	
	// Read load current and wait until it hits 500A +/- 20A error
	load_current = load_current_Read();
	while (load_current < 480 && load_current < 700)	// infinite loop until current reaches 500A
		load_current = load_current_Read();
	
	// read voltage of each cell and store in array once load current reaches 500A 
	LOADED_battery_voltages[0] = batteryCell_read(0);   
	LOADED_battery_voltages[1] = batteryCell_read(5);	// change from PD1 to PD5 because OPAMP uses PD1 and PD4
	LOADED_battery_voltages[2] = batteryCell_read(2);
	LOADED_battery_voltages[3] = batteryCell_read(3);	
	
	/* Tell user to turn off carbon pile load... */
	clear_lcd();
	sprintf(dsp_buff1, "Test complete...");
	sprintf(dsp_buff2, "Rotate Knob until"); 
	sprintf(dsp_buff3, "beeping stops");
	update_lcd();
	
	// Make buzzer beep until current is below 150A
	VPORTC.DIR |= PIN1_bm; // Set PC1 as output
	
	while (load_current > 150)
	{
		load_current = load_current_Read();
		
		VPORTC.OUT |= 0x02;	    // make PC1 output 1, make buzzer beep
		_delay_ms(1000);	    // wait 1 seconds
		VPORTC.OUT &= 0xFD;		// make PC1 output 0, make buzzer quiet
		_delay_ms(1000);		// wait 1 seconds		
	}
	
	set_Fan_PWM(0);
	
	clear_lcd();
	/* Display results... */
	sprintf(dsp_buff1, "B1: %.3f  B1: %.3f",UNLOADED_battery_voltages[0] ,LOADED_battery_voltages[0]); //place voltages in display buffers for each line
	sprintf(dsp_buff2, "B2: %.3f  B2: %.3f",UNLOADED_battery_voltages[1] ,LOADED_battery_voltages[1]);
	sprintf(dsp_buff3, "B3: %.3f  B3: %.3f",UNLOADED_battery_voltages[2] ,LOADED_battery_voltages[2]);
	sprintf(dsp_buff4, "B4: %.3f  B4: %.3f",UNLOADED_battery_voltages[3] ,LOADED_battery_voltages[3]);	
	
	update_lcd();	
}


/* Types interrupts that can be generated by a pushbutton press*/
typedef enum {
	NONE,
	OK, 
	BACK, 
	UP, 
	DOWN
} PB_interrupt;

void (*local_interface_CURRENT_STATE)(PB_interrupt);
local_interface_CURRENT_STATE = &MAIN_MENU;

void MAIN_MENU(PB_interrupt PB_press)
{
	clear_lcd();
	sprintf(dsp_buff1, "Test");
	sprintf(dsp_buff2, "View History");

	switch(PB_press)
	{
		case OK:
			if (cursor_line_position == 1)
			{
				/* If battery voltage < 100mV display ERROR MESSAGE 1, else...*/
				
	/* Perform ADC conversion */
	ADC_startConversion();
	while(ADC_isConversionDone() != 0x01);	// wait for conversion to finish
	ADC_stopConversion();
	adc_value = ADC_read();
	adc_value = adc_value >> 4;//the 12 bit result was left adjusted, so shift right 4 places to fix				
				
				
				
				cursor_line_position = 0;	// turn cursor OFF
				local_interface_CURRENT_STATE = &ROTATE_CLOCKWISE;	
				ROTATE_CLOCKWISE(OK);		
			}
			else
			{
				cursor_line_position = 1;
				local_interface_CURRENT_STATE = &DISPLAY_PREVIOUS_TEST_RESULTS_ENTRIES;
				DISPLAY_PREVIOUS_TEST_RESULTS_ENTRIES(OK);				
			}
			break;
		case BACK:
			return;
			break;
		default:
			if (cursor_line_position == 1)
			{
				cursor_line_position = 2;
			}
			else if (cursor_line_position == 2)
			{
				cursor_line_position = 1;
			}
			break;
	}

		if (cursor_line_position == 1)
		{
			sprintf(dsp_buff1, "<-");
		}
		else if (cursor_line_position == 2)
		{
			sprintf(dsp_buff2, "<-");
		}
		
	update_lcd();
};	
void ERROR_MESSAGE_1(PB_interrupt PB_press)
{
	sprintf(dsp_buff1, "Failed! Ensure");
	sprintf(dsp_buff2, "Proper Connection");		
	sprintf(dsp_buff3, "press OK to");
	sprintf(dsp_buff4, "Continue");
	update_lcd();
};
void ROTATE_CLOCKWISE(PB_interrupt PB_press)
{
	
};
void ROTATE_COUNTER_CLOCKWISE(PB_interrupt PB_press)
{
	
};
void DISPLAY_CURRENT_TEST_RESULTS(PB_interrupt PB_press)
{
	
};
void DISCARD_CURRENT_TEST_RESULTS(PB_interrupt PB_press)
{
	
};
void SAVE_CURRENT_TEST_RESULTS_CONFIRM(PB_interrupt PB_press)
{
	
};
void SAVE_CURRENT_TEST_RESULTS_ENTRIES(PB_interrupt PB_press)
{
	
};
void OVERWRITE_PREVIOUS_TEST_RESULTS(PB_interrupt PB_press)
{
	
};
void DISPLAY_PREVIOUS_TEST_RESULTS_ENTRIES(PB_interrupt PB_press)
{
	
};
void DISPLAY_PREVIOUS_TEST_RESULTS(PB_interrupt PB_press)
{
	
};

// Array of pointers to a function that returns void and accepts a parameter of type PB_interrupt
void (*local_interface_state_handler_func_ptrs[])(PB_interrupt) = {
	MAIN_MENU,
	ERROR_MESSAGE_1,
	ROTATE_CLOCKWISE,
	ROTATE_COUNTER_CLOCKWISE,
	DISPLAY_CURRENT_TEST_RESULTS,
	DISCARD_CURRENT_TEST_RESULTS,
	SAVE_CURRENT_TEST_RESULTS_CONFIRM,
	SAVE_CURRENT_TEST_RESULTS_ENTRIES,
	OVERWRITE_PREVIOUS_TEST_RESULTS,
	DISPLAY_PREVIOUS_TEST_RESULTS_ENTRIES,
	DISPLAY_PREVIOUS_TEST_RESULTS
};
